name: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

permissions: {}

jobs:
  welcome:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello there! 👋 Welcome to the DoubtDesk repository!

            Thank you for opening your first issue. We are thrilled to have you here, especially if you're participating in GSSoC! Please make sure you have carefully read our [Contributing Guidelines](https://github.com/knoxiboy/DoubtDesk/blob/main/CONTRIBUTING.md) to understand our rules and how to request assignment. A maintainer will review your issue shortly.
          pr-message: |
            Hello there! 🎉 Thank you so much for your first pull request to DoubtDesk!

            We really appreciate your contribution. A maintainer will review your code soon. If you are participating in GSSoC, ensure your PR is linked to an open issue. Please make sure you have followed all rules in our [Contributing Guidelines](https://github.com/knoxiboy/DoubtDesk/blob/main/CONTRIBUTING.md). Happy coding!
